SCR_CampaignFaction : "{5EB46557DF2AA24F}Configs/Factions/US.conf" {
 UIInfo SCR_FactionUIInfo "{528C961236B7DCD3}" {
  Name "Chimera PMC"
  Icon "{03874D1C269CF736}Images/small_chma.edds"
  m_sNameUpper "Chimera PMC"
 }
 m_sFactionFlag "{7CB9E5F3A851C900}Images/CHMA_SQUARE_FLAG.edds"
 m_FactionFlagMaterial "{0DFAF196DD75A50D}Assets/Props/Fabric/Flags/Data/Flag_2_3_Everon_CHMA.emat"
 m_aGroupRolePresetConfigs {
  SCR_GroupRolePresetConfig "{6176805F751756E5}" {
   m_aLoadoutResources {
    "{BE7CA93E188A5B58}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Campaign_US_Base.et"
    "{C5574DAD3956486C}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Rifleman_CHMA.et"
    "{3E18CC9634468249}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_GL.et"
    "{61DA6CADADBEFF80}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_MG_CHMA.et"
    "{6648BF10EB8790B8}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Officer_CHMA.et"
    "{E27CC9493BFAF668}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Sniper.et"
    "{4357ABF9CA279803}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Medic_CHMA.et"
   }
  }
  SCR_GroupRolePresetConfig "{61A6B125A59ED77D}" {
   m_aLoadoutResources {
    "{BE7CA93E188A5B58}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Campaign_US_Base.et"
    "{0F6689B491641155}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Sniper.et"
    "{E45F1E163F5CA080}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_SL_CHMA.et"
    "{C9E4FEAF5AAC8D8C}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Medic_CHMA.et"
   }
  }
 }
}